name: CI Pipeline for HTML/CSS/JS

on:
  push:
    branches:
      - main  # Se ejecuta cuando hay un push a la rama "main"
  pull_request:
    branches:
      - main  # También se ejecuta cuando hay un pull request a la rama "main"

jobs:
  validate:
    runs-on: ubuntu-latest  # Usa una máquina virtual con Ubuntu

    steps:
      # Paso 1: Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3  # Descarga el código del repositorio

      # Paso 2: Validar HTML (opcional)
      - name: Validate HTML
        uses: actions/github-script@v6
        with:
          script: |
            const { exec } = require('child_process');
            exec('npx html-validator-cli --quiet', (error, stdout, stderr) => {
              if (error) {
                console.error(`Error: ${error.message}`);
                process.exit(1);
              }
              console.log(stdout);
            });

      # Paso 3: Validar JavaScript (opcional)
      - name: Validate JavaScript
        run: |
          echo "Validando archivos JS..."
          npx eslint .  # Ejecuta ESLint para validar el código JS
          echo "Validación de JS completada."

  deploy:
    if: github.ref == 'refs/heads/main'  # Solo se ejecuta en la rama "main"
    runs-on: ubuntu-latest
    needs: validate  # Depende del job "validate"

    steps:
      # Paso 1: Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Desplegar en GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Carpeta raíz del proyecto
